CREATE TABLE IF NOT EXISTS cars(
    id SERIAL PRIMARY KEY,
    "name" VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    "year" INT NOT NULL,
    price DECIMAL(10,2)
);